### ISSUE TITLE
Implement terminal class with jQuery terminal

### ISSUE THREAD

**Issue by ashwinkjoseph** [The-Programming-Foundation/learningcodesnippets#8]
**Task Description**
Implement the abstract class for the terminal using jQuery Terminal.

In the context of TPF, a terminal should have the following behaviour:
- Accept an HTML Div Element and mount to it while initializing
- Accept custom styles when initializing and should also allow for customization after initialization.
- Should allow the user to type and execute commands
- Should accept a callback function during initialization which will be called whenever a command is executed.
- Should accept an instance of a file system while initializing and use it for executing filesystem related commands.
- Should keep track of previously executed commands 
- Should allow for navigating across previously executed commands.
- Should have a method for toggling the state of the waiting/executing state of the terminal. 
- Should have a method for programmatically writing to the terminal via external programs (basically for displaying the output of executed commands)
- Should have a method for minimizing
- Should have a method for closing

**Acceptance criteria for task**
- [ ] Should be able to mount to any HTML Div Element passed to it while initializing it and should render a jQuery terminal in the HTML Div Element
- [ ] Should accept and apply custom styles when initializing
- [ ] Should pass control to the jQuery terminal instance and the user should be able to type into the terminal
- [ ] Should accept a callback function during initialization which must be called every time the user executes a command on the terminal
- [ ] Should accept an instance of an already initialized filesystem during its initialization and should use it to display directories and allow the user to navigate across the filesystem using the methods defined for a filesystem in #3 
- [ ] Should expose a method for toggling the waiting state of the terminal. During the waiting stage, the terminal must not accept any input and show `waiting..` or `processing...` message
- [ ] Should expose a method through which a string can be passed to the terminal and be displayed on the terminal. If the terminal is in a waiting state, it should remove the waiting message and print it and then display the waiting message again.
